### ISSUE TITLE
Hi！When I'm using the code proivided to evaluate the model, it says that the dimension of the features is 950X96 after GAT,and it cames to the error that the  integrated features cannot be multiplied with FC dimension(300X128), sry to trouble but I wanna know if you have met similiar situations while testing?

### ISSUE THREAD

**Issue by HongpuHuang** [thakurnupur/Graph-Graph#1]

**Comment by thakurnupur** [comment]
This may be a result of not concatenating the features of GAT from the graph and i3d before passing them to the FC layer. 
If you used the model definition for the DAD dataset (SpaceTempGoG_detr_dad), then I suggest you check the input dimensions as you should not encounter this error if you use the same input dimensions as mentioned in the code.  
If you experienced this while using the model for the CCD dataset (SpaceTempGoG_detr_ccd) then it was because of a missing definition of GAT for processing I3D features. I have updated the model file accordingly. 

If you can provide more information on your input and data, I may be able to assist further. 

Thank you for bringing pointing this out!

**Comment by HongpuHuang** [comment]
> This may be a result of not concatenating the features of GAT from the graph and i3d before passing them to the FC layer. If you used the model definition for the DAD dataset (SpaceTempGoG_detr_dad), then I suggest you check the input dimensions as you should not encounter this error if you use the same input dimensions as mentioned in the code. If you experienced this while using the model for the CCD dataset (SpaceTempGoG_detr_ccd) then it was because of a missing definition of GAT for processing I3D features. I have updated the model file accordingly.
> 
> If you can provide more information on your input and data, I may be able to assist further.
> 
> Thank you for bringing pointing this out!

Thank you for your reply! I have updated the model and checked the dataset, and I tried both CCD and DAD, but both of them still ran into the error of dimensional mismatch.This time I check the error, it says that the problem actually arises in the part where the object detection features are passed into the label features at the very beginning as the attach file shows (Sorry I made the wrong description yesterday), and I printed the dimensions of the inputs in this part as 950X96 (CCD results), while the linear layer in the model structure is 300X128, thus causing the dimension mismatch. I then printed the dimension of x and self.input_dim and found that the dimension of x was [950, 4192] and self.input_dim = 4096, which is what caused the 'x_label = self.obj_l_fc(x[:, self.input_dim:])' making the label feature input dimension [950x96]. I wonder if you calculate the feature dimension of x under each graph as [950, 4192] during the experiment? Because by linear layer dimension the feature dimension of x should be [950, 4396], thanks for pointing out if I'm wrong!

And thanks again for the response！

![1714143763844](https://github.com/thakurnupur/Graph-Graph/assets/102850975/f03f419f-9766-42bd-866b-db54cb00b03a)

**Comment by thakurnupur** [comment]
Thank you for providing all the details. I use the object features provided by the authors of [https://github.com/Cogito2012/UString](https://github.com/Cogito2012/UString) which have dimension of 4096. Are you using a different model/code for object detection?

**Comment by HongpuHuang** [comment]
> Thank you for providing all the details. I use the object features provided by the authors of https://github.com/Cogito2012/UString which have dimension of 4096. Are you using a different model/code for object detection?

Thank you for replying. Sorry maybe my description is not accurate enough, I just use your model structure and the provided dataset, I found that 'x_feat' is 4096 dimensions no problem, but the dimension of 'x_label' in the 'graphofgraph.py' file is the total dimension of x minus self.input_dim as showing in the graph, I am showing here that this 'x_label' dimension is 96, may I ask that in your experiment you are getting What is the dimension of 'x_label'? Also is it possible to trouble you to re-upload the dataset?

![Uploading 1714373917921.png…]()

**Comment by SSerendipityy** [comment]
![Uploading 1714373917921.png…]()

**Comment by HongpuHuang** [comment]
Sorry to bother you, I subsequently printed the dimensions of the label feature 'label_embeddings' in dataset_ccd.py and dataset_dad.py and both are 96 dimensions when determining the dimensionality of the label features for the CCD dataset and the DAD dataset, respectively. lol would like to know if you set the x_label linear layer dimension to 300 in the model structure because in your experiment the label feature dimension is 300?

**Comment by thakurnupur** [comment]
Yes, that's right. I use the word embedding with the dimensions=300.
