### ISSUE TITLE
Data downloading

### ISSUE THREAD

**Issue by orsveri** [thakurnupur/Graph-Graph#2]
Hi Nupur, 
Thank you for providing the code, the weights and the data, and congratulations on a nice WACV paper! 
I am very excited to try out Graph(Graph) but I'm struggling a bit with downloading the data - it is going ridiculously slowly, I guess because of the large amount of small files and the need to create a .zip file right during the downloading process.

I believe it would be much easier and faster if you made compressed (.zip) files. 
As CCD data is rather large, instead of one very large zip file that can be difficult to download in case of unstable network, you could make compressed files from subfolders (negative/positive) so it's only 6 compressed files around 10 GB each or so.

**Comment by thakurnupur** [comment]
I appreciate your interest in the paper! @orsveri 
You can download individual folders from the provided link, which may be faster for you.

**Comment by orsveri** [comment]
Thank you for the quick response!
Because of the large number of small files and compressing on the go, even individual folders take a lot of time to download. 
I was able to download the DAD dataset, which is much smaller, and it is enough for me. 
As my goal was just to inform you about this potential problem, I'm closing this issue!
