### ISSUE TITLE
about ccd dataset

### ISSUE THREAD

**Issue by fly-dk** [thakurnupur/Graph-Graph#3]
When I download the CCD dataset, I am always told that the compressed file is corrupted. Can you share this dataset in other ways?

**Comment by fly-dk** [comment]
Thank you！

**Comment by thakurnupur** [comment]
Which folder among the three is showing as corrupted? If you tried downloading the entire folder, could you try individual folders inside the CCD folder? 
You can download the obj_feat folder from [https://github.com/Cogito2012/UString](https://github.com/Cogito2012/UString).

**Comment by fly-dk** [comment]
@thakurnupur Your obj_feat is different from UString. How do you deal with it?

**Comment by thakurnupur** [comment]
@fly-dk The obj_feat is not different from Ustring. We use their obj_feat for both datasets. 
Also, I recommend downloading individual folders inside the CCD dataset to avoid corrupted files and/or longer downloading time.
